### ISSUE TITLE
Got error when testing without "--cuda"

### ISSUE THREAD

**Issue by LevineYang** [ouyanghuiyu/Thundernet_Pytorch#13]
Hi Ouyang,

Great work! Now I've finished the training on Pascal VOC and begin to do the testing job. I got some questions here that 1) the snet_146 model can only run 90FPS+ on RTX2060; 2) when I test without "--cuda", errors pop up... 

Any help is appreciated!

Shun

**Comment by Guzaiwang** [comment]
How much is your final snet_146 model on VOC_2007 ?  I have trained the model for 2 hours and the model achieves a mean AP of 0.6082.

**Comment by LevineYang** [comment]
> How much is your final snet_146 model on VOC_2007 ? I have trained the model for 2 hours and the model achieves a mean AP of 0.6082.

Well, Guzai, the final MAP is about 0.81. I trained the model using RTX2060 for 22 hours.

**Comment by ouyanghuiyu** [comment]
hi,levine! Your MAP is 0.81?That's impossible，Did you change anything？My result is only 0.62，It's still in the works！

**Comment by Guzaiwang** [comment]
> hi,levine! Your MAP is 0.81?That's impossible，Did you change anything？My result is only 0.62，It's still in the works！

Me too~, my final MAP score is also 0.62.

**Comment by ouyanghuiyu** [comment]
yes！ I'm still working on the Data Augmentation

**Comment by Guzaiwang** [comment]
> > How much is your final snet_146 model on VOC_2007 ? I have trained the model for 2 hours and the model achieves a mean AP of 0.6082.
> 
> Well, Guzai, the final MAP is about 0.81. I trained the model using RTX2060 for 22 hours.

Hi, Levine. Could you show me more training details? Thx.

**Comment by LevineYang** [comment]
Sorry buddy, I found it impossible. After thinking about the whole training process, I found I made mistake when splitting dataset and there is overlap between training validation and testing. Sorry for this and can you help me with my issue @ouyanghuiyu

**Comment by AileenXie** [comment]
I have the same problem when I test without "--cuda". How can I run the test in cpu? @ouyanghuiyu

**Comment by Guzaiwang** [comment]
> I have the same problem when I test without "--cuda". How can I run the test in cpu? @ouyanghuiyu
How much is your final snet_146 model on VOC_2007 ?

**Comment by XinYangDong** [comment]
I ran the test in the CPU with the following error:

load checkpoint weights/snet_146/pascal_voc_0712/thundernet_epoch_6.pth
load model successfully!
load checkpoint weights/snet_146/pascal_voc_0712/thundernet_epoch_6.pth
Loaded Photo: 0 images.
/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
  File "demo.py", line 328, in <module>
    rois_label = _RCNN(im_data, im_info, gt_boxes, num_boxes)
  File "/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 126, in forward
    pooled_feat = self._roi_align_layer(base_feat, rois.view(-1, 5))
  File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 68, in _roi_align_layer
    return self.psroiAlign.forward(bottom, rois)
  File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/psroialign.py", line 19, in forward
    pooled_feat = self.psroialign(feat, rois)
  File "/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/PSROIAlign/model/roi_layers/ps_roi_align.py", line 77, in forward
    self.pooled_dim  # 10
  File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/PSROIAlign/model/roi_layers/ps_roi_align.py", line 33, in forward
    raise NotImplementedError
NotImplementedError
