### ISSUE TITLE
CPU测试问题

### ISSUE THREAD

**Issue by senliuy** [ouyanghuiyu/Thundernet_Pytorch#17]
GPU上预测结果一切正常，将代码拷贝到另外一台CPU服务器上，CPU可以运行，但没有预测框。请问作者试过在CPU上运行代码吗？结果是正确的吗？

**Comment by ouyanghuiyu** [comment]
你好，我是准备用onnx推理的，因为一般torch的速度不快。但现在我还没测试

**Comment by duducode** [comment]
你好，请问编译时需要注意哪些问题，我在cpu上运行报错，I ran the test in the CPU with the following error:

load checkpoint weights/snet_146/pascal_voc_0712/thundernet_epoch_6.pth
load model successfully!
load checkpoint weights/snet_146/pascal_voc_0712/thundernet_epoch_6.pth
Loaded Photo: 0 images.
/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/functional.py:1351: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
Traceback (most recent call last):
File "demo.py", line 328, in 
rois_label = _RCNN(im_data, im_info, gt_boxes, num_boxes)
File "/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 126, in forward
pooled_feat = self._roi_align_layer(base_feat, rois.view(-1, 5))
File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/model/faster_rcnn/faster_rcnn.py", line 68, in _roi_align_layer
return self.psroiAlign.forward(bottom, rois)
File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/psroialign.py", line 19, in forward
pooled_feat = self.psroialign(feat, rois)
File "/home/silence/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in call
result = self.forward(*input, **kwargs)
File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/PSROIAlign/model/roi_layers/ps_roi_align.py", line 77, in forward
self.pooled_dim # 10
File "/home/silence/cvdata/Thundernet_Pytorch-master/lib/psroialign/PSROIAlign/model/roi_layers/ps_roi_align.py", line 33, in forward
raise NotImplementedError
NotImplementedError

**Comment by duducode** [comment]
> GPU上预测结果一切正常，将代码拷贝到另外一台CPU服务器上，CPU可以运行，但没有预测框。请问作者试过在CPU上运行代码吗？结果是正确的吗？

请问你解决了了吗
